### ISSUE TITLE
`IsHindrance` Can Lead to Crash

### ISSUE THREAD

**Issue by OfficerSpy** [Vinillia/actions.ext#24]
Using this callback can cause crashes, as it seems to trace back to a function directly [here](https://github.com/alliedmodders/sourcemod/blob/8d234c3b7df340dd85e9089a424eb32b998d196e/core/HalfLife2.cpp#L1096), when used in `ActionPropagation::ProcessMethodArg`. It is believed that this is because it doesn't account for a possible value of `0xffffffff` for CBaseEntity as noted [here](https://github.com/OfficerSpy/TF2-MvM-Defender-TFBots/issues/2#issuecomment-2156237646).

**Comment by Vinillia** [comment]
Thanks for report. Fixed
